[package]
name = "uniprot"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
quick-xml = "*"
url = "*"
fnv = "*"
bytes = "*"

[dev-dependencies]
ftp = "*"
libflate = "*"
