[package]
name = "uniprot"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.3"
err-derive = "0.2.1"
fnv = "1.0.6"
quick-xml = "0.17.2"
url = "2.1.1"

[dev-dependencies]
ftp = "3.0.1"
libflate = "0.1.27"
[dev-dependencies.reqwest]
version = "0.10.0"
features = ["blocking"]
default-features = false
